### ISSUE TITLE
Remove global variables

### ISSUE THREAD

**Issue by shriharshtendulkar** [riyagori1203/RFI-Loc#2] opened 2022-09-14 09:19 UTC
There is no need for global variables in this code. 

Redo parts of canvas.py that use global variables.

**Comment by shriharshtendulkar** [comment] 2022-09-15 12:41
I think this is where you are stuck with the global variables part.

Your button press event functions need to have the form `function(event)` but you also need to pass the `self` pointer so that you can use a variable inside `self` to do all the manipulation you need.

The way to do this is to do the following:
```
class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.view = FigureCanvas(Figure(figsize=(5, 5)))

.
.
        # define some variables here
        self.intersections = [] # here you'll append the dictionaries 
.
.

        self.view.mpl_connect('pick_event', self.on_pick)  # connect it to self.on_pick which will take 'event' as its first argument
.
.

    def on_pick(self, event):  # define the on_pick event as a method of self, not as a independent function.
        # define things here.
        x, y = event.xdata, event.ydata
        self.intersections.append((x,y))

```
Hope this usage is clear.         

Also, I realised that there are two places where you are doing `mpl_connect('pick_event', function)` with different functions. Any specific reason for that?

**Comment by riyagori1203** [comment] 2022-09-16 07:03
Yes yes, the issue is resolved, and the latest code has been pushed. Yes, the issue with calling the function with self.on_pick was that it was a nested function inside plotfile so it couldn't read self as a part of the class, and hence unable to call it using self. But the issue was resolved without its use too.

**Closed as completed by riyagori1203** 2022-09-16 07:03 UTC
